### ISSUE TITLE
Add gesture rotation

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_APDS9960#25]
The APDS9960 is rotated 90 degrees on the CLUE, therefore the gestures are off by 90 degrees.

Add the ability to compensate for sensor rotation by including gesture rotation.

The other capabilities of the sensor are not affected by rotation.

**Comment by kattni** [comment]
@FoamyGuy Let me know if you'd be interested in taking this on.

**Comment by FoamyGuy** [comment]
@kattni I'm definitely willing to give it a try. I think I can do it. Do I understand correctly: user will be able to set rotate to 0, 90, 180, or 270. If the rotation is set then the values returned by `.gesture()` will be manipulated to the desired rotation. i.e. if rotation is 90 and the "real" gesture detected is `1 #UP` instead what will get returned is `4 #RIGHT`

**Comment by evaherrada** [comment]
Solved by #26. Closing
