### ISSUE TITLE
What is a 'clear' color value?

### ISSUE THREAD

**Issue by phelps** [adafruit/Adafruit_CircuitPython_APDS9960#32]
From the [Adafruit documentation](https://learn.adafruit.com/adafruit-apds9960-breakout/circuitpython):

> read the color_data property to retrieve the red, green, blue, and clear color values as a 4-tuple of 16-bit values …

I can't, for the life of me, figure out what a "clear" color value or "clear light" refers to! Deep googling yields information about Tibetan Bhuddism and a psychedelic rock band from the 1960s.

Thanks in advance.

**Comment by ladyada** [comment]
full spectral light - you can check the APDS9960 datasheet for spectral range!

**Comment by dasl-** [comment]
I'm not a color expert, but I feel like I understand the basic concept of RGB values. However, it's not clear to me what "full spectral light" means. If anyone is able to explain further, or provide a link to a good article, please share. Thanks.
