### ISSUE TITLE
no method for setting pgain/ggain

### ISSUE THREAD

**Issue by bablokb** [adafruit/Adafruit_CircuitPython_APDS9960#41]
I know that the policy for this lib is to not expose all registers to keep the footprint small. But I think it really needs methods for setting the proximity-gain (PGAIN) and gesture-gain (GGAIN). The default is 1x and 4x respectively. With  this setting, proximity detection kicks in at a distance below an inch (at least for my sensor), which makes the driver almost useless.

The lib already has a setter/getter for the color-gain (AGAIN), and I would provide a patch with similar methods for the PGAIN/GGAIN settings if you also think this is a useful addition.

**Comment by ladyada** [comment]
Sure, please submit a PR :)

**Comment by bablokb** [comment]
I created pull-request #42
